name: "CI/CD Pipeline"
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '*/**'
  push:
    branches: [ main ]
    paths:
      - '*/**'

jobs:
  build:
    uses: devops4solutions/github-reusable-workflows/.github/workflows/ci.yaml@main
    with:
      ecr-registry: public.ecr.aws/d0p8w4f7/hello-svc:0ce67c5f28dfce3023eb1619433130218c51d6ef
      ecr-repository: hello-svc
      image-tag: ${{ github.sha }}
      jar-name: helloservice-1.jar
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  terraform:
   needs: build
   uses: devops4solutions/github-reusable-workflows/.github/workflows/cd.yaml@main
   with:
     working-directory: terraform
     container_version: ${{ github.sha }}
     environment: dev
   secrets:
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
